model:
  type: resnet
  activation: gelu          # relu|tanh|gelu|silu|leaky_relu

  pooling: avg              # avg|max|none
  cifar_stem: true
  init: kaiming_normal

dataset:
  name: cifar100
  classes: [0, 1, 2, 3, 4]
  shift: 0.0

training:
  optimizer: sgd
  lr: 0.1
  epochs: 2
  batch_size: 128

runs: 1

evaluation:
  num_points: 5
